apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loaduatv5190-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loaduatv5190-tenant-component
    app.kubernetes.io/part-of: loaduatv5190-tenant-app
  name: loaduatv5190-tenant-component
  namespace: loaduatv5190-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loaduatv5190-tenant-component
    weight: null
status: {}
